---
abstract: 'get network device information and gateway'
author:
  - 'GomoR <gomor-cpan_at_gomor.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Frame-Device
no_index:
  directory:
    - t
    - inc
requires:
  Class::Gomor: 1.00
  Net::Frame: 0
  Net::Frame::Dump: 1.08
  Net::Frame::Layer::ICMPv6: 0
  Net::Frame::Layer::IPv6: 0
  Net::Frame::Simple: 0
  Net::IPv4Addr: 0
  Net::IPv6Addr: 0
  Net::Libdnet: 0
  Net::Libdnet6: 0
  Net::Pcap: 0.12
  Net::Write: 1.00
version: 1.07
